#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT=$(dirname $DIR)
PLIST=$PROJECT/ios/FlickerstripApp/Info.plist
MANIFEST=$PROJECT/android/app/src/main/AndroidManifest.xml

VERSION_NUMBER=$1

/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $VERSION_NUMBER" $PLIST
perl -i -pe 's/(?<=android:versionName)=".*"/"'$VERSION_NUMBER'"/' $MANIFEST

if [[ "$2" == "GITADD" ]]; then
    git --git-dir $PROJECT/.git add $PLIST $MANIFEST
fi

