#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT=$(dirname $DIR)
PLIST=$PROJECT/ios/FlickerstripApp/Info.plist

VERSION_NUMBER=$1

/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $VERSION_NUMBER" $PLIST

