#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT=$(dirname $DIR)
PLIST=$PROJECT/ios/FlickerstripApp/Info.plist
MANIFEST=$PROJECT/android/app/src/main/AndroidManifest.xml
APP_GRADLE=$PROJECT/android/app/build.gradle

COMMIT_COUNT=`git --git-dir $PROJECT/.git rev-list --count HEAD`

if [[ "$1" == "PRECOMMIT" ]] || [[ "$2" == "PRECOMMIT" ]]; then
    ((COMMIT_COUNT++))
fi
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $COMMIT_COUNT" $PLIST
perl -i -pe 's/(?<=versionCode )".*"/'$COMMIT_COUNT'/' $APP_GRADLE

if [[ "$1" == "GITADD" ]] || [[ "$2" == "GITADD" ]]; then
    git --git-dir $PROJECT/.git add $PLIST $APP_GRADLE
fi

echo "Updated build number to $COMMIT_COUNT";
