#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

rm -rf build || true
mkdir build
r.js -o build.js
lessc app/style.less > build/style.css
mkdir -p ./build/view/lib
mkdir -p ./build/view/less
cp -r ./app/view/lib/spectrum.css ./build/view/lib/spectrum.css
cp -r ./app/view/less/fonts ./build/view/less/
python buildEditor.py
cp ./build/editor.html $DIR/../android/app/src/main/assets/
